import { Footer } from './components/Footer'
import { NavBar } from './components/NavBar'
import './globals.scss'
import { Oswald } from 'next/font/google';

const oswald  = Oswald({
  weight: ['400', '700'],
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={ `${ oswald.className }` }>
      <div className="navbar"><NavBar /></div>
      <div className="navbar-offset">
        { children }
      </div>
      <Footer></Footer>
      </body>
      </html>
  )
}
